/**
 * Standardized application error codes
 */
export const ERROR_CODES = {
    BAD_REQUEST: "BAD_REQUEST",
    AUTH_REQUIRED: "AUTH_REQUIRED",
    INVALID_TOKEN: "INVALID_TOKEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    FORBIDDEN: "FORBIDDEN",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
    CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
    MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
    INVALID_ID: "INVALID_ID",
    DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    DATABASE_ERROR: "DATABASE_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
};
